// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBRAQau3HCBk4rRXqdk2jRaqUY8Du0gA',
    appId: '1:964231406201:web:7d0a364ae0671f86b66aa8',
    messagingSenderId: '964231406201',
    projectId: 'messxchangenew',
    authDomain: 'messxchangenew.firebaseapp.com',
    storageBucket: 'messxchangenew.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAay1QH7AmTxo-8PWkk2HCS0z3wKRzY4kA',
    appId: '1:964231406201:android:833835ecf07dac70b66aa8',
    messagingSenderId: '964231406201',
    projectId: 'messxchangenew',
    storageBucket: 'messxchangenew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtB3mfcsFTZkhJYkVCmHU51DhVgJ6J70',
    appId: '1:964231406201:ios:0a72da1188814f1db66aa8',
    messagingSenderId: '964231406201',
    projectId: 'messxchangenew',
    storageBucket: 'messxchangenew.firebasestorage.app',
    iosBundleId: 'com.example.messxchangenew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtB3mfcsFTZkhJYkVCmHU51DhVgJ6J70',
    appId: '1:964231406201:ios:0a72da1188814f1db66aa8',
    messagingSenderId: '964231406201',
    projectId: 'messxchangenew',
    storageBucket: 'messxchangenew.firebasestorage.app',
    iosBundleId: 'com.example.messxchangenew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpBRAQau3HCBk4rRXqdk2jRaqUY8Du0gA',
    appId: '1:964231406201:web:d8aea5e4a058e7dab66aa8',
    messagingSenderId: '964231406201',
    projectId: 'messxchangenew',
    authDomain: 'messxchangenew.firebaseapp.com',
    storageBucket: 'messxchangenew.firebasestorage.app',
  );
}
